name = "DataTypesBasic"
uuid = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "2.0.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3"
julia = "1.6"
# for all Julia versions below 1.6 we now get an error... 
# really surprising, but we go for 1.6 then, as a new LTS version will come soon.

# ERROR: LoadError: LoadError: StackOverflowError:
# Stacktrace:
#  [1] top-level scope at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/promote_type.jl:105
#  [2] include(::Function, ::Module, ::String) at ./Base.jl:380
#  [3] include at ./Base.jl:368 [inlined]
#  [4] include(::String) at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/DataTypesBasic.jl:34
#  [5] top-level scope at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/DataTypesBasic.jl:53
#  [6] include(::Function, ::Module, ::String) at ./Base.jl:380
#  [7] include(::Module, ::String) at ./Base.jl:368
#  [8] top-level scope at none:2
#  [9] eval at ./boot.jl:347 [inlined]
#  [10] eval(::Expr) at ./client.jl:467
#  [11] top-level scope at ./none:3
# in expression starting at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/promote_type.jl:105
# in expression starting at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/DataTypesBasic.jl:53
# ERROR: LoadError: Failed to precompile DataTypesBasic [83eed652-29e8-11e9-12da-a7c29d64ffc9] to /home/runner/.julia/compiled/v1.5/DataTypesBasic/qwg4x_PPMzj.ji.
# Stacktrace:
#  [1] error(::String) at ./error.jl:33
#  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
#  [3] _require(::Base.PkgId) at ./loading.jl:1030
#  [4] require(::Base.PkgId) at ./loading.jl:928
#  [5] require(::Module, ::Symbol) at ./loading.jl:923
#  [6] include(::String) at ./client.jl:457
#  [7] top-level scope at none:6
# in expression starting at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/test/runtests.jl:2

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
