name = "DataTypesBasic"
uuid = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3"
julia = "1.3"
# This package is not compatible with julia 1.0
# Either: Error During Test at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/test/Either.jl:6
#   Test threw exception
#   Expression: getrightOption(Either{String}(3)) == Option(3)
#   MethodError: Union{Nothing, Identity{T}} where T(::Int64) is ambiguous. Candidates:
#     (::Type{Union{Nothing, Identity{T}}})(a::T) where T in DataTypesBasic at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/Option.jl:6
#     (::Type{Union{Nothing, Identity{T}} where T})(a::T) where T in DataTypesBasic at /home/runner/work/DataTypesBasic.jl/DataTypesBasic.jl/src/Option.jl:8
#   Possible fix, define
#     Nothing(::T)
# TODO check whether this might be added to 1.0.X somewhen

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
