name = "DataTypesBasic"
uuid = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "2.0.2"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3, 4"
julia = "1.6"

[extras]
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor"]
