name = "DataTypesBasic"
uuid = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"

[compat]
Compat = "2.1, 3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
